---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml
  tasks:
    - name: create App host
      digital_ocean_droplet:
        name: "{{apphost_name}}"
        oauth_token: "{{ do_token }}"
        size: "{{ apphost_size }}"
        region: "{{ apphost_region }}"
        image: "{{ apphost_image }}"
        wait_timeout: 600
        unique_name: yes
        state: present
        unique_name: yes
        ssh_keys: ["{{apphost_ssh_key}}"]
      register: apphost
  
    - name: store app host ip
      set_fact:
        apphost_ip: "{{apphost.data.ip_address}}"
  
    - name: make DNS record for app host
      digital_ocean_domain:
        name: "{{domain}}"
        ip: "{{apphost.data.ip_address}}"
        oauth_token: "{{do_token}}"
