---

- hosts: app
  remote_user: root
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml
  tasks:

    - name: install pip
      apt:
        name: python3-pip
        update_cache: yes
        state: present

    - name: install docker module
      pip:
        name: docker

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Create directory structure
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/djavue/frontend/www
        - /opt/djavue/frontend/caddy
        - /opt/djavue/frontend/config
        - /opt/djavue/backend/data
        - /opt/djavue/backend/config

    - name: Put Django prod config
      ansible.builtin.template:
        src: ./prod_settings.py.j2
        dest: /opt/djavue/backend/config/prod.py

    - name: Start backend container
      docker_container:
        name: "djavue-backend"
        image: "{{backend_image}}"
        state: started
        container_default_behavior: "no_defaults"
        volumes:
          - /opt/djavue/backend/config/prod.py:/app/djavue/settings/prod.py
          - /opt/djavue/backend/data:/app/djavue/data
        env:
          DJANGO_SETTINGS_MODULE: "djavue.settings.prod"
        command: sleep inf 
        restart_policy: "unless-stopped"
      register: backend_docker_info
      
    - name: Put Caddy config
      template:
        src: ./Caddyfile.j2
        dest: /opt/djavue/frontend/config/Caddyfile

    - name: Build frontend
      local_action: ansible.builtin.command cd ../frontend/ && yarn build 
 
    - name: Upload frontend files
      ansible.posix.synchronize:
        src: ../frontend/dist/
        dest: /opt/djavue/frontend/www

    - name: Start frontend container
      docker_container:
        name: "djavue-frontend"
        image: "{{frontend_image}}"
        state: started
        container_default_behavior: "no_defaults"
        published_ports:
          - 0.0.0.0:80:80
          - 0.0.0.0:443:443
        volumes:
          - /opt/djavue/frontend/config/Caddyfile:/etc/caddy/Caddyfile
          - /opt/djavue/frontend/data:/data
          - /opt/djavue/frontend/www:/var/www
        restart_policy: "unless-stopped"
